<HomePage>:
    FloatLayout:
        canvas:
            Rectangle:
                size: self.size
                pos: self.pos
                source:'icones/fundo.jpg'
        Label:
            pos_hint: {'right':1, 'top': 1}
            size_hint: 1, 0.85
            text:'Homepage'

        Button:
            pos_hint: {'right':1, 'top': 0.15}
            size_hint: 0.33, 0.15
            text: 'ir para menu'
            on_release: app.mudar_tela('menupage')